fix typo in readme X10 != X11

diff --git a/README b/README
--- a/README
+++ b/README
@@ -1,19 +1,37 @@
 
-# 1st try to build with cmake
+CWD=$PWD
+
 MISSING_REQ=0
-for req in cmake make;do
+for req in mktemp wget unzip;do
 	type $req >/dev/null 2>&1 || { echo >&2 "Missing dependency: $req"; MISSING_REQ=1; }
 done
-[ $MISSING_REQ -eq 0 ] && { mkdir build; cd build; cmake ..; make; exit 0;}
 
+[ $MISSING_REQ -ne 0 ] && { echo "Aborting because of missing dependency"; exit 1; }
 
-# 2nd try to build with compiler 
-MISSING_REQ=0
-for req in cc;do
-	type $req >/dev/null 2>&1 || { echo >&2 "Missing dependency: $req"; MISSING_REQ=1; }
-done
-[ $MISSING_REQ -eq 0 ] && { mkdir build; cd build; cc -lX10 -L/usr/include/X11 ../scr2ppm.c -o scr2ppm; exit 0;}
+ZIPFILE=$(mktemp)
+EXTRDIR=$(mktemp -d)
 
-# i give up 
-echo "build failed, no useable compiler or build system found"
+wget -q --show-progress https://github.com/igorlogius/src2ppm/archive/master.zip -O $ZIPFILE
 
+unzip -j $ZIPFILE "src2ppm-master/scr2ppm.c" -d $EXTRDIR 
+unzip -j $ZIPFILE "src2ppm-master/CMakeLists.txt" -d $EXTRDIR 
+
+cd $EXTRDIR
+
+type cmake >/dev/null 2>&1;CM_RET=$?
+type cc >/dev/null 2>&1;CC_RET=$?
+
+if [ $CM_RET -eq 0 ];then
+    cmake . && make
+elif [ $CC_RET -eq 0];then
+    cc -lX11 -L/usr/include/X11 ./scr2ppm.c -o scr2ppm; 
+fi
+
+if [ -x ./scr2ppm ];then
+	mv scr2ppm $CWD/; 
+	echo "build succeded"
+else
+	echo "build failed, no useable compiler or build system found";
+fi
+
+rm -rf $EXTRDIR/ $ZIPFILE
